server:
  port: 8080

firebase:
  credentials:
    # 放在 resources 下直接用 classpath
    path: classpath:firebase-service-account.json
  # 项目 id，可以在 Firebase 控制台 Project settings 里看到
  project-id: mytest-62127
  database-url: https://mytest-62127-default-rtdb.asia-southeast1.firebasedatabase.app

  #https://<你的项目ID>-default-rtdb.firebaseio.com
